### PR TITLE
[NOMERGE] Test macOS CI workflow without Roswell

### PR DESCRIPTION
**Pull request by ak-coram**

### CODE REVIEW

**Comment by catap** [comment]
FYI: https://github.com/ivmai/bdwgc/pull/576

**Comment by catap** [comment]
@ak-coram may I ask you to add `-DDEBUG_THREADS` into cflags? :)

**Comment by catap** [comment]
The fix inside ECL: https://gitlab.com/embeddable-common-lisp/ecl/-/merge_requests/303

**Comment by catap** [comment]
This fix allows to pass CI a few time in the row

**Comment by catap** [comment]
Fix inside ecl `develop` branch... Updated the code.

**Comment by catap** [comment]
Seems quite stable now. Thanks to discover how to reproduce it. I do have encountered it before but haven't able to reproduce it.

**Comment by ak-coram** [comment]
@catap thanks for the investigation and the fixes! Let me know if you still need this PR, otherwise I'll close it.

**Comment by catap** [comment]
The fix were merged into upstream => nothing to do with that on my side.

but it is sadly that such issue were discovered after release and to be fixed in the released version we must wait quite a long time :(

**Comment by ak-coram** [comment]
> but it is sadly that such issue were discovered after release and to be fixed in the released version we must wait quite a long time :(

@catap I agree, hopefully it's not two and a half years this time :(

**Comment by catap** [comment]
who knows. BTW I've created patch which was merged on 23.9.9 branch which allows me to easy backport it to MacPorts: https://github.com/macports/macports-ports/pull/20581

So, technically you may use https://gitlab.com/embeddable-common-lisp/ecl/-/commit/e8c9355d31e15d15900416e9925db56c54c9f265 as root and enjoy ECL-23.9.9 with that patch at your CI.

**Pull request closed without merging**
